name: Deploy Project
on: [push, workflow_dispatch]
jobs:
  tests:
  #Ubuntu-latest already comes with node@16
    runs-on: ubuntu-latest
    steps:
      - name: Get code from GH repo
        uses: actions/checkout@v3
      - name: Install Node Js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install client dependencies
        run: npm install
      - name: Run unit tests 
        run: npm test 
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get code from GH repo
        uses: actions/checkout@v3
      - name: Install Node Js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install client dependencies
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."